server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-connections: 20000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/questionnaire?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: 123456
mvc:
  static-path-pattern: /static/**
resources:
  static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.model
logging:
  level:
    edu:
      taru:
        api: INFO
        mapper: DEBUG
pattern:
  console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n  '
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:

